# Generated by Django 5.1.1 on 2024-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapstep',
            options={'ordering': ['order'], 'verbose_name': 'Roadmap Step', 'verbose_name_plural': 'Roadmap Steps'},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='progress',
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
