# Generated by Django 5.1.1 on 2024-10-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_roadmapstep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=20),
        ),
    ]
