# Generated by Django 5.1.1 on 2024-10-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_userprogress_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapstep',
            options={},
        ),
    ]
