# Generated by Django 5.1.1 on 2024-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_roadmapstep_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vowel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('sound', models.CharField(max_length=50)),
            ],
        ),
    ]
