# Generated by Django 5.1.1 on 2024-10-14 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_vowel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_left', models.CharField(max_length=255)),
                ('e_factor', models.FloatField(default=0.5)),
                ('interval', models.FloatField(default=1.0)),
                ('half_life', models.FloatField(default=2.0)),
                ('time_interval', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
